on: [push]

jobs:
  register-workflow-job:
    runs-on: ubuntu-latest
    name: register a workflow
    steps:
    - name: register
      id: register
      uses: stuzart/workflowhub-register-action@v2
    - with:
        workflow-file: 'test.cwl'
	api-token: 'hhh'	
	api-user: 'xxx'
    - name: Get the output
      run: echo "The resutl was ${{ steps.register.outputs.result }}"
